#pragma once
static char *parition_types[256] = {
	"Unused partition",
	"12-bit FAT (remember: this is on hard disks, not floppy disks, so youll rarely see this today). ",
	"XENIX root",
	"XENIX /usr (obsolete)",
	"16-bit FAT, partition; of sizes less than 32 MB.",
	"Extended Partition, (also see 0F below).",
	"16-bit FAT, partition; greater than or equal to 32 MB.",
	"Installable file systems: HPFS or NTFS. Also, QNX and Advanced Unix. ",
	"AIX bootable partition, AIX (Linux), SplitDrive, OS/2 (through Version 1.3), Dell partition spanning multiple drives (array), Commodore DOS.",
	"AIX data partition, AIX bootable (Linux), Coherent file system, QNX. ",
	"Coherent swap partition, OPUS or OS/2 Boot Manager. ",
	"32-bit FAT",
	"32-bit FAT, using LBA Extensions.",
	 "NOT USED",
	"16-bit FAT >= 32 MB, using LBA Extensions. ",
	"Extended Partition, using LBA Extensions; often means it begins past 1024 cylinders. ",
	"OPUS ",
	"Hidden 12-bit FAT.",
	"Compaq diagnostics.",
	 "NOT USED",
	"Hidden 16-bit FAT, partition <32 MB, Novell DOS 7.0 (result of bug in FDISK?),AST DOS with logical sectored FAT.",
	 "NOT USED",
	"Hidden 16-bit FAT, partition >= 32 MB ",
	"Hidden IFS (HPFS, NTFS). ",
	"AST Windows swap file ",
	"Willowtech Photon coS ",
	 "NOT USED",
	"Hidden 32-bit FAT ",
	"Hidden 32-bit FAT, Ext LBA ",
	 "NOT USED",
	"Hidden 16-bit FAT >32 MB, Ext. LBA (PowerQuest specific) ",
	 "NOT USED",
	"Willowsoft Overture File System (OFS1) ",
	"reserved (HP Volume Expansion, SpeedStor variant) Oxygen FSo2",
	"Oxygen Extended ",
	"reserved (HP Volume Expansion, SpeedStor variant?) ",
	"NEC MS-DOS 3.x ",
	 "NOT USED",
	"reserved (HP Volume Expansion, SpeedStor variant?) ",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	"reserved (HP Volume Expansion, SpeedStor variant?) ",
	 "NOT USED",
	"reserved (HP Volume Expansion, SpeedStor variant?) ",
	"reserved (HP Volume Expansion, SpeedStor variant?) ",
	 "NOT USED",
	"reserved (HP Volume Expansion, SpeedStor variant?) ",
	 "NOT USED",
	"Theos ",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	"PowerQuest Files Partition Format ",
	"Hidden NetWare ",
	 "NOT USED",
	 "NOT USED",
	"VENIX 80286 ",
	"Personal RISC Boot, PowerPC boot partition, PTS-DOS 6.70 & BootWizard: Alternative Linux, Minix and DR-DOS.",
	"Secure File System, Windows 2000/XP (NT 5): Dynamic extended partition PTS-DOS 6.70 & BootWizard: Alternative Linux swap and DR-DOS.",
	"Alternative Linux native file system (EXT2fs) PTS-DOS 6.70 & BootWizard: DR-DOS",
	 "NOT USED",
	"Priam, EUMEL/Elan. ",
	"EUMEL/Elan ",
	"EUMEL/Elan ",
	"EUMEL/Elan ",
	 "NOT USED",
	"ALFS/THIN lightweight filesystem for DOS ",
	 "NOT USED",
	 "NOT USED",
	"QNX ",
	"QNX ",
	"QNX, Oberon boot/data partition. ",
	"Ontrack Disk Manager, read-only partition, FAT partition (Logical sector size varies) ",
	"Ontrack Disk Manager, read/write partition, FAT partition (Logical sector size varies) Novell ?",
	"CP/M, Microport System V/386. ",
	"Ontrack Disk Manager, write-only ",
	"Ontrack Disk Manager 6.0 (DDO) ",
	"EZ-Drive 3.05 ",
	"Golden Bow VFeature ",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	"Priam EDISK ",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	"Storage Dimensions SpeedStor ",
	 "NOT USED",
	"GNU HURD, Mach, MtXinu BSD 4.2 on Mach, Unix Sys V/386, 386/ix. ",
	"Novell NetWare 286, SpeedStore. ",
	"Novell NetWare (3.11 and 4.1) ",
	"Novell NetWare 386 ",
	"Novell NetWare ",
	"Novell NetWare ",
	"Novell NetWare 5+; Novell Storage Services (NSS) ",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	"DiskSecure Multi-Boot ",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	"IBM PC/IX ",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	"Minix v1.1 - 1.4a, Old MINIX (Linux). ",
	"Linux/Minix v1.4b+, Mitac Advanced Disk Manager. ",
	"Linux Swap partition, Prime or Solaris (Unix). ",
	"Linux native file systems (ext2/3/4, JFS, Reiser, xiafs, and others).",
	"OS/2 hiding type 04h partition or APM hibernation, can be used by Win98.)",
	 "NOT USED",
	"NT Stripe Set, Volume Set? ",
	"NT Stripe Set, Volume Set?, HPFS FT mirrored partition. ",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	"Amoeba file system, Hidden Linux EXT2 partition (PowerQuest). ",
	"Amoeba bad block table ",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	"Mylex EISA SCSI ",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	"BSDI",
	"Phoenix NoteBios Power Management 'Save to Disk', IBM hibernation. ",
	"HP Volume Expansion (SpeedStor variant) ",
	 "NOT USED",
	"HP Volume Expansion (SpeedStor variant) ",
	"HP Volume Expansion (SpeedStor variant) ",
	"FreeBSD/386 ",
	"OpenBSD ",
	"HP Volume Expansion (SpeedStor variant) ",
	"NextStep Partition ",
	"NetBSD ",
	"Olivetti DOS with FAT12 ",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	"Bootmanager BootStar by Star-Tools GmbH ",
	"HP Volume Expansion (SpeedStor variant) ",
	 "NOT USED",
	"HP Volume Expansion (SpeedStor variant) ",
	"HP Volume Expansion (SpeedStor variant) ",
	 "NOT USED",
	"HP Volume Expansion (SpeedStor variant) ",
	"BSDI file system or secondarily swap ",
	"BSDI swap partition or secondarily file system ",
	 "NOT USED",
	 "NOT USED",
	"PTS BootWizard (hidden) 4.0; but now also used by Acronis OS Selector to hide or create some partitions.",
	"May be an Acronis 'Backup' or 'Secure Zone' partition, when labeled 'ACRONIS SZ' (FAT32, LBA mapped, primary).",
	 "NOT USED",
	"Solaris boot partition ",
	 "NOT USED",
	"Novell DOS/OpenDOS/DR-OpenDOS/DR-DOS secured partition, or CTOS (reported by a client).",
	"DR-DOS 6.0 LOGIN.EXE-secured 12-bit FAT partition ",
	"Reserved for DR-DOS 7+ ",
	"Reserved for DR-DOS 7+ ",
	"DR-DOS 6.0 LOGIN.EXE-secured 16-bit FAT partition ",
	 "NOT USED",
	"DR-DOS 6.0 LOGIN.EXE-secured Huge partition, or Corrupted FAT16 volume/stripe (V/S) set (Windows NT).",
	"Syrinx, Cyrnix, HPFS FT disabled mirrored partition, or Corrupted NTFS volume/stripe set.",
	"Reserved for DR-DOS 7+ ",
	"Reserved for DR-DOS 7+ ",
	"Reserved for DR-DOS 7+ ",
	"Reserved for DR-DOS secured FAT32 ",
	"Reserved for DR-DOS secured FAT32X (LBA) ",
	"Reserved for DR-DOS 7+ ",
	"Reserved for DR-DOS secured FAT16X (LBA) ",
	"Reserved for DR-DOS secured Extended partition (LBA) ",
	"Multiuser DOS secured (FAT12???) ",
	"Old Multiuser DOS secured FAT12 ",
	 "NOT USED",
	 "NOT USED",
	"Old Multiuser DOS secured FAT16 (<= 32M) ",
	"Old Multiuser DOS secured extended partition ",
	"Old Multiuser DOS secured FAT16 (BIGDOS > 32 Mb) ",
	 "NOT USED",
	"CP/M 86 ",
	 "NOT USED",
	 "NOT USED",
	"CP/M, Concurrent CP/M, Concurrent DOS, or CTOS (Convergent Technologies OS).",
	 "NOT USED",
	 "NOT USED",
	"Dell partition. Normally it contains a FAT16 file system of about 32 MB.",
	"BootIt EMBRM ",
	 "NOT USED",
	"SpeedStor 12-bit FAT Extended partition, DOS access (Linux). ",
	"DOS read-only (Florian Painke's XFDISK 1.0.4) ",
	"SpeedStor (Norton, Linux says DOS R/O) ",
	"SpeedStor 16-bit FAT Extended partition ",
	"Tandy DOS with logical sectored FAT ",
	"Storage Dimensions SpeedStor ",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	"BeOS file system ",
	 "NOT USED",
	"Reserved for Matthias Paul's Spryt*x ",
	"Indicates a GPT Protective MBR followed by a GPT/EFI Header. Used to define a fake partition covering the entire disk.",
	"UEFI System Partition; defines a UEFI system partition (or ESP). On Windows PCs, the ESP contains the NTLDR, HAL, Boot.txt, and other files that are needed to boot the system, such as drivers. The Partition GUID defines the ESP: '(PARTITION_SYSTEM_GUID, 0xC12A7328L, 0xF81F, 0x11D2, 0xBA, 0x4B, 0x00, 0xA0, 0xC9, 0x3E, 0xC9, 0x3B)' Note: MBR disks can also have ESPs. UEFI specifies booting from either GPT or MBR. The ESP on an MBR disk is also identified by type 0xEF. However, Windows does not support booting UEFI from MBR disks or 0xEF partitions. (Reference: http://msdn.microsoft.com/en-us/library/windows/hardware/gg463525.aspx.)",
	 "NOT USED",
	"SpeedStor Dimensions (Norton,Landis) ",
	"DOS 3.3+ second partition, Unisys DOS with logical sectored FAT. ",
	"Storage Dimensions SpeedStor ",
	"SpeedStor Storage Dimensions (Norton,Landis) ",
	"Prologue ",
	"Storage Dimensions SpeedStor ",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	 "NOT USED",
	"Reserved for FreeDOS (http://www.freedos.org) ",
	"LANstep, IBM PS/2 IML (Initial Microcode Load) partition, or Storage Dimensions SpeedStor (> 1024 cylinder?).)",
	"Xenix bad-block table "
};
